### ISSUE TITLE
请教一下Appkey 是哪里获取？

### ISSUE THREAD

**Issue by JasonQWJ** [tangclQaQ/BOpenliveSDK-UE4#2]
请教一下Appkey 是哪里获取？ 还是要开发平台上自己建一个？

**Comment by tangclQaQ** [comment]
https://open-live.bilibili.com

去B站那边申请一个开发者账号，申请后去后台创建一个应用，这样你就能获得插件里init函数需要的所有参数了。

**Comment by JasonQWJ** [comment]
@tangclQaQ 感谢 我了解到了，创建的应用无所谓是什么，随便传个文件。 其他api的接入是在您这个插件里走的对吗？

**Comment by tangclQaQ** [comment]
是的，填好需要的参数之后，就能获取到对应的事件了，可以加官方Q群798641197

**Comment by JasonQWJ** [comment]
感谢 已经通了

**Comment by JasonQWJ** [comment]
感谢大佬 无私奉献
