### ISSUE TITLE
一直在重连，不明白是什么原因，接收不到弹幕

### ISSUE THREAD

**Issue by GuoPuS** [tangclQaQ/BOpenliveSDK-UE4#4]
LogTemp: WebSocket is closed, Reason is Successfully closed connection to our peer
LogTemp: websocket re connect
LogTemp: WebSocket is not connected
LogTemp: WebSocket is closed, Reason is Successfully closed connection to our peer
LogTemp: websocket re connect
LogTemp: WebSocket is not connected
LogTemp: WebSocket is closed, Reason is Successfully closed connection to our peer
LogTemp: websocket re connect
LogTemp: WebSocket is not connected
LogTemp: WebSocket is closed, Reason is Successfully closed connection to our peer
LogTemp: websocket re connect
LogTemp: WebSocket is not connected
LogTemp: WebSocket is closed, Reason is Successfully closed connection to our peer
LogTemp: websocket re connect
LogTemp: WebSocket is not connected
LogTemp: WebSocket is closed, Reason is Successfully closed connection to our peer
LogTemp: websocket re connect
LogTemp: websocket re connect
LogTemp: WebSocket is not connected
LogTemp: websocket re connect
LogTemp: WebSocket is not connected
LogTemp: WebSocket is closed, Reason is Successfully closed connection to our peer
LogTemp: WebSocket is not connected
LogTemp: websocket re connect
LogTemp: 发送心跳包响应成功。

**Comment by tangclQaQ** [comment]
确认下填的数据是不是自己的数据，以及看下自己申请的应用是不是互动玩法类型的&nbsp;


....
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月11日(星期二) 晚上8:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [tangclQaQ/BOpenliveSDK-UE4] 一直在重连，不明白是什么原因，接收不到弹幕 (Issue #4)





 
LogTemp: WebSocket is closed, Reason is Successfully closed connection to our peer
 LogTemp: websocket re connect
 LogTemp: WebSocket is not connected
 LogTemp: WebSocket is closed, Reason is Successfully closed connection to our peer
 LogTemp: websocket re connect
 LogTemp: WebSocket is not connected
 LogTemp: WebSocket is closed, Reason is Successfully closed connection to our peer
 LogTemp: websocket re connect
 LogTemp: WebSocket is not connected
 LogTemp: WebSocket is closed, Reason is Successfully closed connection to our peer
 LogTemp: websocket re connect
 LogTemp: WebSocket is not connected
 LogTemp: WebSocket is closed, Reason is Successfully closed connection to our peer
 LogTemp: websocket re connect
 LogTemp: WebSocket is not connected
 LogTemp: WebSocket is closed, Reason is Successfully closed connection to our peer
 LogTemp: websocket re connect
 LogTemp: websocket re connect
 LogTemp: WebSocket is not connected
 LogTemp: websocket re connect
 LogTemp: WebSocket is not connected
 LogTemp: WebSocket is closed, Reason is Successfully closed connection to our peer
 LogTemp: WebSocket is not connected
 LogTemp: websocket re connect
 LogTemp: 发送心跳包响应成功。

**Comment by GuoPuS** [comment]
是自己申请的开发者信息，
![image](https://user-images.githubusercontent.com/84904820/231169864-9e1b85e5-0fc2-490c-b7d7-ea9b864c9864.png)
是互动类的项目。

**Comment by tangclQaQ** [comment]
798641197
加下B站官方的交流群，有空我远程你看看

**Comment by GuoPuS** [comment]
嗯，我加下，谢谢！

**Comment by GuoPuS** [comment]
可以了，使用插件的时候不能挂科技。
